name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Setup Node.js (required for npm version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Ensure output folder exists
      - name: Create output folder
        run: mkdir -p dist

      # Step 4: Generate GitHub Snake using npm version
      - name: Generate GitHub Snake
        uses: platane/snk@v3
        with:
          github_user_name: AkshayBhujbal1995
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      # Step 5: Commit and push changes if any
      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/*
          git diff --cached --quiet || git commit -m "Update GitHub Snake"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
